
package resources;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PlayerService", targetNamespace = "http://classes.server.org/", wsdlLocation = "http://localhost:1802/WS/Player?wsdl")
public class PlayerService
    extends Service
{

    private final static URL PLAYERSERVICE_WSDL_LOCATION;
    private final static WebServiceException PLAYERSERVICE_EXCEPTION;
    private final static QName PLAYERSERVICE_QNAME = new QName("http://classes.server.org/", "PlayerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1802/WS/Player?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PLAYERSERVICE_WSDL_LOCATION = url;
        PLAYERSERVICE_EXCEPTION = e;
    }

    public PlayerService() {
        super(__getWsdlLocation(), PLAYERSERVICE_QNAME);
    }

    public PlayerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PLAYERSERVICE_QNAME, features);
    }

    public PlayerService(URL wsdlLocation) {
        super(wsdlLocation, PLAYERSERVICE_QNAME);
    }

    public PlayerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PLAYERSERVICE_QNAME, features);
    }

    public PlayerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PlayerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Player
     */
    @WebEndpoint(name = "PlayerPort")
    public Player getPlayerPort() {
        return super.getPort(new QName("http://classes.server.org/", "PlayerPort"), Player.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Player
     */
    @WebEndpoint(name = "PlayerPort")
    public Player getPlayerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://classes.server.org/", "PlayerPort"), Player.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PLAYERSERVICE_EXCEPTION!= null) {
            throw PLAYERSERVICE_EXCEPTION;
        }
        return PLAYERSERVICE_WSDL_LOCATION;
    }

}
